Update panel elements, fix bugs
KronikarzIO/Frontend pull request #12
Opened 2021-01-16 13:59 UTC by DanielPiatek

2021-01-16 15:11 UTC, Blazevarjo requested changes
Trzeba by tu dodać obsługę z api

2021-01-16 15:11 UTC, Blazevarjo commented on pages/edit-tree.html
To wszystko powinno być formą i zawierać atrybuty name odpowiadające modelowi w api

2021-01-16 15:11 UTC, Blazevarjo commented on scripts/edit-tree.js
> +
Jaki to ma cel?

2021-01-16 15:11 UTC, Blazevarjo commented on scripts/edit-tree.js
> +	document.getElementById("deathCauseInfo").innerHTML = user.deathCause;
Gdzie jest zdefiniowany user? Te wartości można jedną linijką wyciagnąć z formy

2021-01-19 14:26 UTC, RANDOM-V2N5q commented
Panel informacji o osobie został napisany

2021-01-19 14:26 UTC, closed without merging